apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-tree-d3
  description: |
    This is an old forked repo that I'm using for backstage testing.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: zwk5004/react-tree-d3
spec:
  type: service
  owner: guest
  lifecycle: experimental
